{% set name = "openinference-semantic-conventions" %}
{% set version = "0.1.39" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/openinference_semantic_conventions-{{ version }}.tar.gz
  sha256: e7ca74d297f9fa166c5bad871195e24582da35861039ccb459103cda81a354ad

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - openinference.semconv.trace

about:
  summary: OpenInference Semantic Conventions
  home: https://github.com/Arize-ai/openinference
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - michaelschiff
    - mikeldking
    - RogerHYang
    - axiomofjoy
    - anticorrelator
